name: teaolive
author: vvakame <vvakame+dev@gmail.com>
version: 0.0.6
homepage: http://vvakame.github.io/teaolive/
description: BDD testing framework for Dart
dependencies:
  http: 0.9.2+3
dev_dependencies:
  browser: any
