name: teaolive
version: 0.0.7
author: vvakame <vvakame+dev@gmail.com>
description: BDD testing framework for Dart
homepage: http://vvakame.github.io/teaolive/
dependencies:
  http: 0.9.2+3
dev_dependencies:
  browser: any
